---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.0.0
    hooks:
      - id: no-commit-to-branch

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.13.0
    hooks:
      - id: yamllint
