version: '3'
services:
  rdphoney:
    build:
      context: .
      dockerfile: Dockerfile
    image: rdphoney:latest
    volumes:
      - configs:/etc/rdphoney/
    env_file:
      - rdphoney.env
volumes:
  configs:
